import { LiveDataCommandRepository } from '../../../src/live-data/repositories/live-data-command.repository';
import { PrismaService } from '../../../src/prisma/prisma.service';

describe('LiveDataCommandRepository', () => {
  let prisma: jest.Mocked<PrismaService>;
  let repository: LiveDataCommandRepository;

  beforeEach(() => {
    prisma = {
      liveDataCommand: {
        create: jest.fn(),
      },
    } as any;

    repository = new LiveDataCommandRepository(prisma);
  });

  it('uses Prisma create so id and timestamps are generated by Prisma defaults', async () => {
    (prisma.liveDataCommand.create as jest.Mock).mockResolvedValue({
      id: 'command-1',
      organizationId: 'org-1',
      agentId: 'agent-1',
      liveDataSessionId: null,
      commandType: 'CLEAR_DTC',
      payload: { diagnosticSessionId: 'session-1' },
      consumedAt: null,
      createdAt: new Date(),
    });

    await repository.enqueue({
      organizationId: 'org-1',
      agentId: 'agent-1',
      liveDataSessionId: null,
      commandType: 'CLEAR_DTC',
      payload: { diagnosticSessionId: 'session-1' },
    });

    expect(prisma.liveDataCommand.create).toHaveBeenCalledWith({
      data: {
        organizationId: 'org-1',
        agentId: 'agent-1',
        liveDataSessionId: null,
        commandType: 'CLEAR_DTC',
        payload: { diagnosticSessionId: 'session-1' },
      },
    });
  });
});
