export enum ScanJobStatus {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  NEEDS_VEHICLE_CONFIRMATION = 'NEEDS_VEHICLE_CONFIRMATION',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}
